create table USER_INFO (
    uSER_ID INT,
	USERNAME VARCHAR2(30),
	EMAIL VARCHAR2(30),
	PASSWORD VARCHAR2(30),
	LVL INT
);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (1, 'Cookley', '1@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (2, 'Konklux', '2@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (3, 'Lotstring', '3@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (4, 'Fix San', '4@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (5, 'Tresom', '5@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (6, 'Sonair', '6@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (7, 'Cardguard', '7@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (8, 'Overhold', '8@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (9, 'Prodder', '9@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (10, 'Stronghold', '10@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (11, 'Regrant', '11@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (12, 'Y-find', '12@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (13, 'It', '13@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (14, 'Gembucket', '14@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (15, 'Duobam', '15@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (16, 'Ronstring', '16@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (17, 'Tampflex', '17@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (18, 'Ventosanzap', '18@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (19, 'Opela', '19@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (20, 'Fix San', '20@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (21, 'Fintone', '21@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (22, 'Gembucket', '22@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (23, 'Opela', '23@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (24, 'Zontrax', '24@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (25, 'Zoolab', '25@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (26, 'Regrant', '26@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (27, 'Holdlamis', '27@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (28, 'Alphazap', '28@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (29, 'Opela', '29@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (30, 'Lotstring', '30@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (31, 'Flowdesk', '31@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (32, 'Lotlux', '32@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (33, 'Latlux', '33@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (34, 'Bitwolf', '34@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (35, 'Bigtax', '35@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (36, 'Duobam', '36@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (37, 'Bitwolf', '37@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (38, 'Flowdesk', '38@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (39, 'Daltfresh', '39@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (40, 'Span', '40@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (41, 'Greenlam', '41@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (42, 'Zamit', '42@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (43, 'Latlux', '43@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (44, 'Vagram', '44@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (45, 'Regrant', '45@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (46, 'Sub-Ex', '46@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (47, 'Temp', '47@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (48, 'Gembucket', '48@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (49, 'Vagram', '49@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (50, 'Fixflex', '50@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (51, 'Sonair', '51@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (52, 'Bigtax', '52@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (53, 'Lotlux', '53@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (54, 'Andalax', '54@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (55, 'Bamity', '55@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (56, 'Latlux', '56@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (57, 'Fix San', '57@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (58, 'Keylex', '58@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (59, 'Fix San', '59@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (60, 'Hatity', '60@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (61, 'Latlux', '61@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (62, 'Cookley', '62@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (63, 'Duobam', '63@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (64, 'Treeflex', '64@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (65, 'Vagram', '65@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (66, 'Mat Lam Tam', '66@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (67, 'Sonsing', '67@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (68, 'Span', '68@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (69, 'Tres-Zap', '69@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (70, 'Zathin', '70@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (71, 'Voltsillam', '71@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (72, 'Alphazap', '72@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (73, 'Bitwolf', '73@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (74, 'Mat Lam Tam', '74@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (75, 'Zathin', '75@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (76, 'Fix San', '76@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (77, 'Alphazap', '77@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (78, 'Subin', '78@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (79, 'Temp', '79@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (80, 'Keylex', '80@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (81, 'Ronstring', '81@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (82, 'Transcof', '82@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (83, 'Matsoft', '83@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (84, 'Zoolab', '84@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (85, 'Otcom', '85@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (86, 'Ventosanzap', '86@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (87, 'Stronghold', '87@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (88, 'Span', '88@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (89, 'Zathin', '89@gmail.com', 1, 1);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (90, 'Fixflex', '90@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (91, 'Cardify', '91@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (92, 'Biodex', '92@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (93, 'Home Ing', '93@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (94, 'Prodder', '94@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (95, 'It', '95@gmail.com', 1, 4);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (96, 'Flowdesk', '96@gmail.com', 1, 5);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (97, 'Quo Lux', '97@gmail.com', 1, 2);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (98, 'Namfix', '98@gmail.com', 1, 3);
insert into USER_INFO (uSER_ID, USERNAME, EMAIL, PASSWORD, LVL) values (99, 'Job', '99@gmail.com', 1, 5);
